project:
  type: website
  output-dir: docs

website:
  title: "Tyler Moseley"
  favicon: favicon.png
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
    tools:
    - icon: twitter
      href: https://twitter.com/tylermmoseley
    - icon: github
      menu:
        - text: GitHub Profile
          url: https://github.com/tylermoseley
        - text: This Page's Source
          url:  https://github.com/tylermoseley/tylermoseley.github.io
        - text: Report a Bug
          url:  https://github.com/tylermoseley/tylermoseley.github.io/issues/new

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false
    code-fold: true