project:
  type: website
  output-dir: docs

website:
  title: "Tyler Moseley"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd
    tools:
    - icon: twitter
      href: https://twitter.com
    - icon: github
      menu:
        - text: Source Code
          url:  https://code.com
        - text: Report a Bug
          url:  https://bugs.com

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false