project:
  type: website
  output-dir: docs

website:
  title: "Tyler Moseley"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - projects.qmd

format:
  html:
    theme: sandstone
    css: styles.css
    toc: false